ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-noble"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG

USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

### Envrionment config 
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    SMB_SERVER="" \
    SMB_SHARE="" \
    SMB_USER="" \
    SMB_PASSWORD="" \
    INST_SCRIPTS="/ubuntu/install/brave/install_brave.sh \
                  /ubuntu/install/discord/install_discord.sh \
                  /ubuntu/install/gtk/install_restricted_file_chooser.sh \
                  /ubuntu/install/misc/configure_thunar.sh \
                  /ubuntu/install/misc/set_wallpaper.sh \
                  /ubuntu/install/misc/customize_xfce_menu.sh \
                  /ubuntu/install/conky/install_conky.sh \
                  /ubuntu/install/misc/install_welcome_message.sh \
                  /ubuntu/install/cleanup/cleanup.sh"

# Copy install scripts
COPY ./src/ $INST_DIR
COPY ./src/ubuntu/install/misc/custom_startup.sh $STARTUPDIR/custom_startup.sh

# Run installations
RUN \
  chmod +x $STARTUPDIR/custom_startup.sh && \
  for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT} || exit 1; \
  done && \
  mkdir -p /mnt/SAS && \
  bash ${INST_DIR}/ubuntu/install/misc/single_app_security.sh -t && \
  $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/kasm-user && \
  chown -R 1000:0 /home/kasm-user && \
  rm -Rf ${INST_DIR}

# Userspace Runtime
ENV HOME /home/kasm-user
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]